### ISSUE TITLE
maxLength property shows "invalid value" error when given multidigit number

### ISSUE THREAD

**Issue by Zuuja** [jackwootton/json-schema#25]
When editing string assertions and min/max length on https://www.jsonschema.net/ it shows "invalid value" when the number has more than one digit (e.g. '32', '10').

The value is saved anyway so it is a bit confusing but doesn't affect generating schema.

**Comment by jackwootton** [comment]
This has been fixed in the new version (not yet released). Thanks for taking the time to report this. The problem was caused by html input patter being set to `[0-9]` rather than `^\d+$`.

**Comment by tloriato** [comment]
I'm still receiving this error, it only works for single digit numbers right now.

**Comment by vstanchev** [comment]
getting this as well, is it going to be released?

**Comment by jackwootton** [comment]
The new version is now generally available; www.jsonschema.net
