### ISSUE TITLE
Responsiveness broken

### ISSUE THREAD

**Issue by blag001** [jackwootton/json-schema#8]
When your resize the windows with the default JSON, you end with a horizontal scroll bar : 

![image](https://user-images.githubusercontent.com/6142277/36644000-ed088f28-1a53-11e8-80e9-647003cf4c3c.png)

BTW, could be nice to put the break point on `min-width: 992px` (over half of a 16:9 - 1920*1080p).

**Comment by jackwootton** [comment]
This is due to longs strings not wrapping. There should be a nice CSS trick to get this working (I used it for long IDs in the edit view), however, for some reason, it's being overridden by  some material CSS. This is top priority for me and in theory should be an easy fix.

Thanks for adding a bug for this!

**Comment by jackwootton** [comment]
This should be fixed now. Let me know if it's working for you.

**Comment by blag001** [comment]
ok, you'll hate me XD

Mostly Ok, but between `950px` and `957px` body width, you still have the scroll...

For the break-point, it's on `< 950` ? `≤ 950px` will be great (So I'll be on the more adapted mobile mode when using half my screen)

**Comment by jackwootton** [comment]
Can add a screenshot? I can't reproduce this.  The schema should always wrap and the responsive breakpoint is on  `fxFlex.sm` and `fxFlex.xs`. See [Responsive API](https://github.com/angular/flex-layout/wiki/Responsive-API) for pixel details

**Comment by blag001** [comment]
![image](https://user-images.githubusercontent.com/6142277/36735735-250161b4-1bd7-11e8-8b4c-25a7df760d4c.png)

`fxFlex.sm` seem to use `max-width: 959px`, strange... I'll try this at home.

**Comment by jackwootton** [comment]
Is that Edge? or Ie?

**Comment by blag001** [comment]
I'm a bit offended...
Firefox last windows version, same with FF v56 on linux, it's the same with chromium v64 /linux and the outdated Chrome Windows I have under my hand.

It happen exactly just before the switch, for the size of the scroll barre.
